export const answers = {
  basic_vicious_win: "",
  basic_vicious_lose: "",
  basic_vicious_tie: "",
  special_vicious_win: "",
  special_vicious_lose: "",
  special_vicious_tie: "",
  basic_strike_win: "",
  basic_strike_lose: "",
  basic_strike_tie: "",
  special_strike_win: "",
  special_strike_lose: "",
  special_strike_tie: "",
  power_win: "",
  power_lose: "",
  power_tie: "",
  super_win: "",
  super_lose: "",
  super_tie: "",
};
