export const moveSet = [
  {
    name: "Chokeslam",
    image: "/moveImgs/Special_Move_Chokeslam.png",
    Rarity: "Common",
    Type: "Vicious",
    dmg: 210,
    category: "Special Vicious",
  },
  {
    name: "Super Chokeslam",
    image: "/moveImgs/Special_Move_Super_Chokeslam.png",
    Rarity: "Rare",
    Type: "Vicious Chargeable",
    dmg: 230,
    category: "Special Vicious",
  },
  {
    name: "Goal Shot",
    image: "/moveImgs/Special_Move_Goal_Shot.png",
    Rarity: "Common",
    Type: "",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Rekt Shot",
    image: "/moveImgs/Special_Move_Rekt_Shot.png",
    Rarity: "Rare",
    Type: "",
    dmg: 180,
    category: "Special Strike",
  },
  {
    name: "Cozmo Shot",
    image: "/moveImgs/Special_Move_Cozmo_Shot.png",
    Rarity: "Epic",
    Type: "",
    dmg: 210,
    category: "Special Strike",
  },
  {
    name: "Volley Dive",
    image: "/moveImgs/Special_Move_Volley_Dive.png",
    Rarity: "Rare",
    Type: "",
    dmg: 100,
    category: "Special Strike",
  },
  {
    name: "Dolphin Dive",
    image: "/moveImgs/Special_Move_Dolphin_Dive.png",
    Rarity: "Epic",
    Type: "",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Ruby Crusher",
    image: "/moveImgs/Special_Move_Ruby_Crusher.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 250,
    category: "Special Strike",
  },
  {
    name: "Emerald Crusher",
    image: "/moveImgs/Special_Move_Emerald_Crusher.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 280,
    category: "Special Strike",
  },
  {
    name: "Diamond Crusher",
    image: "/moveImgs/Special_Move_Stone_Crusher.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 316,
    category: "Special Strike",
  },
  {
    name: "Vicious Mist",
    image: "/moveImgs/Special_Move_Vicious_Mist.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 100,
    category: "Special Vicious",
  },
  {
    name: "Bad Breath",
    image: "/moveImgs/Special_Move_Bad_Breath.png",
    Rarity: "Rare",
    Type: "Poison",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Big Swing",
    image: "/moveImgs/Special_Move_Big_Swing.png",
    Rarity: "Rare",
    Type: "Vicious ",
    dmg: 94,
    category: "Special Vicious",
  },
  {
    name: "Giant Swing",
    image: "/moveImgs/Special_Move_Giant_Swing.png",
    Rarity: "Epic",
    Type: "Vicious ",
    dmg: 213,
    category: "Special Vicious",
  },
  {
    name: "Punchline",
    image: "/moveImgs/Special_Move_Punchline.png",
    Rarity: "Common",
    Type: "",
    dmg: 250,
    category: "Special Strike",
  },
  {
    name: "Atomic Punchline",
    image: "/moveImgs/Special_Move_Atomic_Punchline.png",
    Rarity: "Rare",
    Type: "",
    dmg: 300,
    category: "Special Strike",
  },
  {
    name: "Cyclone",
    image: "/moveImgs/Special_Move_Cyclone.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Super Cyclone",
    image: "/moveImgs/Special_Move_Super_Cyclone.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 130,
    category: "Special Strike",
  },
  {
    name: "Omega Cyclone",
    image: "/moveImgs/Special_Move_Omega_Cyclone.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Superkick",
    image: "/moveImgs/Special_Move_Superkick.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Superduper Kick",
    image: "/moveImgs/Special_Move_Superduper_Kick.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 195,
    category: "Special Strike",
  },
  {
    name: "Tackle",
    image: "/moveImgs/Special_Move_Tackle.png",
    Rarity: "Common",
    Type: "Vicious",
    dmg: 270,
    category: "Special Vicious",
  },
  {
    name: "Spear Tackle",
    image: "/moveImgs/Special_Move_Spear_Tackle.png",
    Rarity: "Rare",
    Type: "Vicious",
    dmg: 300,
    category: "Special Vicious",
  },
  {
    name: "Javelin Tackle",
    image: "/moveImgs/Special_Move_Javelin_Tackle.png",
    Rarity: "Epic",
    Type: "Vicious",
    dmg: 300,
    category: "Special Vicious",
  },
  {
    name: "SumoSlap",
    image: "/moveImgs/Special_Move_SumoSlap.png",
    Rarity: "Common",
    Type: "",
    dmg: 110,
    category: "Special Strike",
  },
  {
    name: "PoisonSlap",
    image: "/moveImgs/Special_Move_PoisonSlap.png",
    Rarity: "Rare",
    Type: "Chargeable Poison",
    dmg: 110,
    category: "Special Strike",
  },
  {
    name: "Super SumoSlap",
    image: "/moveImgs/Special_Move_Super_SumoSlap.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 130,
    category: "Special Strike",
  },
  {
    name: "Uppercut",
    image: "/moveImgs/Special_Move_Uppercut.png",
    Rarity: "Common",
    Type: "High Priority",
    dmg: 160,
    category: "Power",
  },
  {
    name: "Bionic Uppercut",
    image: "/moveImgs/Special_Move_Bionic_Uppercut.png",
    Rarity: "Rare",
    Type: "High Priority Chargeable",
    dmg: 180,
    category: "Power",
  },
  {
    name: "Omega Uppercut",
    image: "/moveImgs/Special_Move_Omega_Uppercut.png",
    Rarity: "Epic",
    Type: "High Priority Chargeable",
    dmg: 200,
    category: "Power",
  },
  {
    name: "Rocket Jump",
    image: "/moveImgs/Special_Move_Rocket_Jump.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Skyrocket",
    image: "/moveImgs/Special_Move_Skyrocket.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Good IzunaDrop",
    image: "/moveImgs/Special_Move_Good_IzunaDrop.png",
    Rarity: "Rare",
    Type: "Vicious ",
    dmg: 225,
    category: "Special Strike",
  },
  {
    name: "Great IzunaDrop",
    image: "/moveImgs/Special_Move_Great_IzunaDrop.png",
    Rarity: "Epic",
    Type: "Vicious ",
    dmg: 250,
    category: "Special Vicious",
  },
  {
    name: "Left Click Attack",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Basic Strike",
    dmg: 30,
    category: "Basic Strike",
  },
  {
    name: "Innate Basic Vicious",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Basic Vicious Strike",
    dmg: 120,
    category: "Basic Vicious",
  },
  {
    name: "Super",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Super",
    dmg: 720,
    category: "Super",
  },

  // WEAPONS //
  {
    name: "Blue Bat",
    image: "/moveImgs/Weapon_Blue_Bat.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 110,
    viciousDMG: 170,
    category: "Item",
    thrown: 120,
  },
  {
    name: "Comercial Garbage Can",
    image: "/moveImgs/Weapon_Garbage_Can_Commerical.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 120,
    viciousDMG: 125,
    category: "Item",
    thrown: 250,
  },
  {
    name: "House Garbage Can",
    image: "/moveImgs/Weapon_Garbage_Can_House.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 150,
    viciousDMG: 150,
    category: "Item",
    thrown: 250,
  },
  {
    name: "Green Bat",
    image: "/moveImgs/Weapon_Green_Bat.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 100,
    viciousDMG: 150,
    category: "Item",
    thrown: 100,
  },
  {
    name: "Commercial Mail Box",
    image: "/moveImgs/Weapon_Mail_Box_Commerical.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 195,
    viciousDMG: 227,
    category: "Item",
    thrown: 270,
  },
  {
    name: "House Mail Box",
    image: "/moveImgs/Weapon_Mail_Box_House.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 260,
    viciousDMG: 234,
    category: "Item",
    thrown: 170,
  },
  {
    name: "Left One Way Sign",
    image: "/moveImgs/Weapon_One_Way_Sign_Left.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 286,
    viciousDMG: 286,
    category: "Item",
    thrown: 250,
  },
  {
    name: "Plastic Chair",
    image: "/moveImgs/Weapon_Plastic_Chair.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 104,
    viciousDMG: 182,
    category: "Item",
    thrown: 130, //
  },
  {
    name: "Red Folding Chair",
    image: "/moveImgs/Weapon_Red_Folding_Chair.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 90,
    viciousDMG: 90,
    category: "Item",
    thrown: 110,
  },
  {
    name: "Stop Sign",
    image: "/moveImgs/Weapon_Stop_Sign.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 180,
    viciousDMG: 234,
    category: "Item",
    thrown: 210,
  },
  {
    name: "Wooden Folding Chair",
    image: "/moveImgs/Weapon_Wooden_Folding_Chair.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 80,
    viciousDMG: 70,
    category: "Item",
    thrown: 90,
  },
  {
    name: "Wooden Plank",
    image: "/moveImgs/Weapon_Wooden_Plank.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 234,
    viciousDMG: 130,
    category: "Item",
    thrown: 100,
  },
  {
    name: "Yield Sign",
    image: "/moveImgs/Weapon_Yield_Sign.png",
    Rarity: "",
    Type: "Wieldable Weapon",
    dmg: 260,
    viciousDMG: 260,
    category: "Item",
    thrown: 230,
  },
  {
    name: "Wooden Loot Crate",
    image: "/moveImgs/Loot_Crate_Common.png",
    Rarity: "Common",
    Type: "Wieldable Weapon",
    dmg: 260,
    viciousDMG: 162,
    category: "Item",
    thrown: 200,
  },
  {
    name: "Gold Loot Crate",
    image: "/moveImgs/Loot_Crate_Epic.png",
    Rarity: "Epic",
    Type: "Wieldable Weapon",
    dmg: 390,
    viciousDMG: 292,
    category: "Item",
    thrown: 250,
  },
  {
    name: "Silver Loot Crate",
    image: "/moveImgs/Loot_Crate_Rare.png",
    Rarity: "Rare",
    Type: "Wieldable Weapon",
    dmg: 235,
    viciousDMG: 227,
    category: "Item",
    thrown: 250,
  },
];
