export const moveSet = [
  {
    name: "Chokeslam",
    image: "/moveImgs/Special_Move_Chokeslam.png",
    Rarity: "Common",
    Type: "Vicious",
    dmg: 210,
    category: "Special Vicious",
  },
  {
    name: "Super Chokeslam",
    image: "/moveImgs/Special_Move_Super_Chokeslam.png",
    Rarity: "Rare",
    Type: "Vicious Chargeable",
    dmg: 230,
    category: "Special Vicious",
  },
  {
    name: "Goal Shot",
    image: "/moveImgs/Special_Move_Goal_Shot.png",
    Rarity: "Common",
    Type: "",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Rekt Shot",
    image: "/moveImgs/Special_Move_Rekt_Shot.png",
    Rarity: "Rare",
    Type: "",
    dmg: 180,
    category: "Special Strike",
  },
  {
    name: "Cozmo Shot",
    image: "/moveImgs/Special_Move_Cozmo_Shot.png",
    Rarity: "Epic",
    Type: "",
    dmg: 210,
    category: "Special Strike",
  },
  {
    name: "Volley Dive",
    image: "/moveImgs/Special_Move_Volley_Dive.png",
    Rarity: "Rare",
    Type: "",
    dmg: 100,
    category: "Special Strike",
  },
  {
    name: "Dolphin Dive",
    image: "/moveImgs/Special_Move_Dolphin_Dive.png",
    Rarity: "Epic",
    Type: "",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Ruby Crusher",
    image: "/moveImgs/Special_Move_Ruby_Crusher.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 250,
    category: "Special Strike",
  },
  {
    name: "Emerald Crusher",
    image: "/moveImgs/Special_Move_Emerald_Crusher.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 280,
    category: "Special Strike",
  },
  {
    name: "Diamond Crusher",
    image: "/moveImgs/Special_Move_Stone_Crusher.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 316,
    category: "Special Strike",
  },
  {
    name: "Vicious Mist",
    image: "/moveImgs/Special_Move_Vicious_Mist.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 20,
    category: "Special Strike",
  },
  {
    name: "Bad Breath",
    image: "/moveImgs/Special_Move_Bad_Breath.png",
    Rarity: "Rare",
    Type: "Poison",
    dmg: 20,
    category: "Special Strike",
  },
  {
    name: "Big Swing",
    image: "/moveImgs/Special_Move_Big_Swing.png",
    Rarity: "Rare",
    Type: "Vicious ",
    dmg: 94,
    category: "Special Strike",
  },
  {
    name: "Giant Swing",
    image: "/moveImgs/Special_Move_Giant_Swing.png",
    Rarity: "Epic",
    Type: "Vicious ",
    dmg: 213,
    category: "Special Vicious",
  },
  {
    name: "Punchline",
    image: "/moveImgs/Special_Move_Punchline.png",
    Rarity: "Common",
    Type: "",
    dmg: 250,
    category: "Special Strike",
  },
  {
    name: "Atomic Punchline",
    image: "/moveImgs/Special_Move_Atomic_Punchline.png",
    Rarity: "Rare",
    Type: "",
    dmg: 300,
    category: "Special Strike",
  },
  {
    name: "Cyclone",
    image: "/moveImgs/Special_Move_Cyclone.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Super Cyclone",
    image: "/moveImgs/Special_Move_Super_Cyclone.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 130,
    category: "Special Strike",
  },
  {
    name: "Omega Cyclone",
    image: "/moveImgs/Special_Move_Omega_Cyclone.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Superkick",
    image: "/moveImgs/Special_Move_Superkick.png",
    Rarity: "Common",
    Type: "Chargeable",
    dmg: 170,
    category: "Special Strike",
  },
  {
    name: "Superduper Kick",
    image: "/moveImgs/Special_Move_Superduper_Kick.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 195,
    category: "Special Strike",
  },
  {
    name: "Tackle",
    image: "/moveImgs/Special_Move_Tackle.png",
    Rarity: "Common",
    Type: "Vicious",
    dmg: 270,
    category: "Special Vicious",
  },
  {
    name: "Spear Tackle",
    image: "/moveImgs/Special_Move_Spear_Tackle.png",
    Rarity: "Rare",
    Type: "Vicious",
    dmg: 300,
    category: "Special Vicious",
  },
  {
    name: "Javelin Tackle",
    image: "/moveImgs/Special_Move_Javelin_Tackle.png",
    Rarity: "Epic",
    Type: "Vicious",
    dmg: 300,
    category: "Special Vicious",
  },
  {
    name: "SumoSlap",
    image: "/moveImgs/Special_Move_SumoSlap.png",
    Rarity: "Common",
    Type: "",
    dmg: 110,
    category: "Special Strike",
  },
  {
    name: "PoisonSlap",
    image: "/moveImgs/Special_Move_PoisonSlap.png",
    Rarity: "Rare",
    Type: "Chargeable Poison",
    dmg: 110,
    category: "Special Strike",
  },
  {
    name: "Super SumoSlap",
    image: "/moveImgs/Special_Move_Super_SumoSlap.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 130,
    category: "Special Strike",
  },
  {
    name: "Uppercut",
    image: "/moveImgs/Special_Move_Uppercut.png",
    Rarity: "Common",
    Type: "High Priority",
    dmg: 160,
    category: "Power",
  },
  {
    name: "Bionic Uppercut",
    image: "/moveImgs/Special_Move_Bionic_Uppercut.png",
    Rarity: "Rare",
    Type: "High Priority Chargeable",
    dmg: 180,
    category: "Power",
  },
  {
    name: "Omega Uppercut",
    image: "/moveImgs/Special_Move_Omega_Uppercut.png",
    Rarity: "Epic",
    Type: "High Priority Chargeable",
    dmg: 200,
    category: "Power",
  },
  {
    name: "Rocket Jump",
    image: "/moveImgs/Special_Move_Rocket_Jump.png",
    Rarity: "Rare",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Skyrocket",
    image: "/moveImgs/Special_Move_Skyrocket.png",
    Rarity: "Epic",
    Type: "Chargeable",
    dmg: 120,
    category: "Special Strike",
  },
  {
    name: "Good IzunaDrop",
    image: "/moveImgs/Special_Move_Good_IzunaDrop.png",
    Rarity: "Rare",
    Type: "Vicious ",
    dmg: 225,
    category: "Special Strike",
  },
  {
    name: "Great IzunaDrop",
    image: "/moveImgs/Special_Move_Great_IzunaDrop.png",
    Rarity: "Epic",
    Type: "Vicious ",
    dmg: 250,
    category: "Special Strike",
  },
  {
    name: "Left Click Attack",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Basic Strike",
    dmg: 30,
    category: "Basic Strike",
  },
  {
    name: "Innate Basic Vicious",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Basic Vicious Strike",
    dmg: 30,
    category: "Basic Vicious",
  },
  {
    name: "Super",
    image: "/moveImgs/basic_punch.png",
    Rarity: "Innate",
    Type: "Super",
    dmg: 760,
    category: "Super",
  },
];
